version: "3"

networks:
  main:

services:
  click_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - main

  skill_service:
     build:
        dockerfile: Dockerfile.main
        context: .
     ports:
       - "8080:8080"
     environment:
       - PORT=:8080
       - THREADS=2
       - CLICK_HOST=click_server
       - CLICK_PORT=9000
       - CLICK_USER=user
       - CLICK_PASS=user
       - CLICK_DB=metric
     depends_on:
       - click_server
     networks:
       - main
#  click_client:
#    image: yandex/clickhouse-client
#    command: ['--host', 'server']